In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r'C:\Users\prayu\OneDrive\Desktop\Eda_football\EDA_Premier_League_Players\data\Football.csv')

In [11]:
df.shape

(571, 59)

In [12]:
df.head(10)

,Name,Jersey Number,Club,Position,Nationality,Age,Appearances,Wins,Losses,Goals,...,Punches,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides
0,Bernd Leno,1.0,Arsenal,Goalkeeper,Germany,28.0,64,28,16,0,...,34.0,26.0,17.0,28.0,375.0,489.0,2,0,0,NaN
1,Matt Macey,33.0,Arsenal,Goalkeeper,England,26.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN
2,Rúnar Alex Rúnarsson,13.0,Arsenal,Goalkeeper,Iceland,25.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN
3,Héctor Bellerín,2.0,Arsenal,Defender,Spain,25.0,160,90,37,7,...,NaN,NaN,NaN,NaN,NaN,NaN,23,0,125,8.0
4,Kieran Tierney,3.0,Arsenal,Defender,Scotland,23.0,16,7,5,1,...,NaN,NaN,NaN,NaN,NaN,NaN,2,0,9,0.0
5,William Saliba,4.0,Arsenal,Defender,France,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
6,Sokratis,5.0,Arsenal,Defender,Greece,32.0,44,21,11,3,...,NaN,NaN,NaN,NaN,NaN,NaN,18,0,56,1.0
7,Rob Holding,16.0,Arsenal,Defender,England,25.0,41,25,9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,8,0,32,0.0
8,Shkodran Mustafi,20.0,Arsenal,Defender,Germany,28.0,99,52,26,7,...,NaN,NaN,NaN,NaN,NaN,NaN,28,0,117,7.0
9,Calum Chambers,21.0,Arsenal,Defender,England,25.0,139,47,57,6,...,NaN,NaN,NaN,NaN,NaN,NaN,28,1,137,2.0

In [ ]:
df

In [26]:
df.isnull().sum().sort_values(ascending=False)

Throw outs                502
Sweeper clearances        502
Catches                   502
High Claims               502
Punches                   502
Penalties saved           502
Saves                     502
Goal Kicks                502
Last man tackles          378
Clearances off line       378
Goals conceded            309
Own goals                 309
Clean sheets              309
Freekicks scored          262
Shots                     262
Penalties scored          262
Goals per match           262
Shots on target           262
Shooting accuracy %       262
Big chances missed        262
Aerial battles won        181
Recoveries                181
Successful 50/50s         181
Duels lost                181
Duels won                 181
Aerial battles lost       181
Tackle success %          181
Cross accuracy %          181
Through balls             181
Accurate long balls       112
Errors leading to goal    112
Interceptions              69
Headed Clearance           69
Clearances                 69
Big chances created        69
Offsides                   69
Crosses                    69
Blocked shots              69
Tackles                    69
Headed goals               69
Goals with left foot       69
Hit woodwork               69
Goals with right foot      69
Jersey Number               8
Nationality                 1
Age                         1
Club                        0
Losses                      0
Wins                        0
Goals                       0
Position                    0
Appearances                 0
Name                        0
Assists                     0
Passes                      0
Passes per match            0
Yellow cards                0
Red cards                   0
Fouls                       0
dtype: int64

In [42]:
df[df['Goals conceded'].notnull()][['Goals conceded','Name','Position','Appearances']]

     Goals conceded                  Name    Position  Appearances
0              82.0            Bernd Leno  Goalkeeper           64
1               0.0            Matt Macey  Goalkeeper            0
2               0.0  Rúnar Alex Rúnarsson  Goalkeeper            0
3             166.0       Héctor Bellerín    Defender          160
4              16.0        Kieran Tierney    Defender           16
..              ...                   ...         ...          ...
554            18.0         Rúben Vinagre    Defender           34
555             2.0     Maximilian Kilman    Defender            4
556             0.0            Oskar Buur    Defender            1
557             0.0                Marçal    Defender            2
558             0.0        Ki-Jana Hoever    Defender            0

[262 rows x 4 columns]

In [44]:
df[df['Last man tackles'].isnull()][['Last man tackles','Name','Position','Appearances']]

     Last man tackles                  Name    Position  Appearances
0                 NaN            Bernd Leno  Goalkeeper           64
1                 NaN            Matt Macey  Goalkeeper            0
2                 NaN  Rúnar Alex Rúnarsson  Goalkeeper            0
13                NaN            Mesut Özil  Midfielder          184
14                NaN        Lucas Torreira  Midfielder           63
..                ...                   ...         ...          ...
566               NaN            Pedro Neto     Forward           31
567               NaN          Raúl Jiménez     Forward           78
568               NaN          Adama Traoré     Forward          105
569               NaN           Fábio Silva     Forward            1
570               NaN      Leonardo Campana     Forward            0

[378 rows x 4 columns]

In [51]:
df[(df['Last man tackles'].notnull())&(df['Position']=='Defender')][['Last man tackles','Name','Position','Appearances']]

     Last man tackles               Name  Position  Appearances
3                 1.0    Héctor Bellerín  Defender          160
4                 0.0     Kieran Tierney  Defender           16
5                 0.0     William Saliba  Defender            0
6                 1.0           Sokratis  Defender           44
7                 1.0        Rob Holding  Defender           41
..                ...                ...       ...          ...
554               0.0      Rúben Vinagre  Defender           34
555               0.0  Maximilian Kilman  Defender            4
556               0.0         Oskar Buur  Defender            1
557               0.0             Marçal  Defender            2
558               0.0     Ki-Jana Hoever  Defender            0

[191 rows x 4 columns]

In [38]:
df[df['Saves'].notnull()][['Saves','Name','Position']]

     Saves                  Name    Position
0    222.0            Bernd Leno  Goalkeeper
1      0.0            Matt Macey  Goalkeeper
2      0.0  Rúnar Alex Rúnarsson  Goalkeeper
30   408.0            Tom Heaton  Goalkeeper
31     2.0             Jed Steer  Goalkeeper
..     ...                   ...         ...
521   15.0          David Martin  Goalkeeper
522   85.0       Darren Randolph  Goalkeeper
523    0.0          Nathan Trott  Goalkeeper
549  195.0          Rui Patrício  Goalkeeper
550  389.0            John Ruddy  Goalkeeper

[69 rows x 3 columns]

In [15]:
df.dtypes

Name                       object
Jersey Number             float64
Club                       object
Position                   object
Nationality                object
Age                       float64
Appearances                 int64
Wins                        int64
Losses                      int64
Goals                       int64
Goals per match           float64
Headed goals              float64
Goals with right foot     float64
Goals with left foot      float64
Penalties scored          float64
Freekicks scored          float64
Shots                     float64
Shots on target           float64
Shooting accuracy %        object
Hit woodwork              float64
Big chances missed        float64
Clean sheets              float64
Goals conceded            float64
Tackles                   float64
Tackle success %           object
Last man tackles          float64
Blocked shots             float64
Interceptions             float64
Clearances                float64
Headed Clearance          float64
Clearances off line       float64
Recoveries                float64
Duels won                 float64
Duels lost                float64
Successful 50/50s         float64
Aerial battles won        float64
Aerial battles lost       float64
Own goals                 float64
Errors leading to goal    float64
Assists                     int64
Passes                      int64
Passes per match          float64
Big chances created       float64
Crosses                   float64
Cross accuracy %           object
Through balls             float64
Accurate long balls       float64
Saves                     float64
Penalties saved           float64
Punches                   float64
High Claims               float64
Catches                   float64
Sweeper clearances        float64
Throw outs                float64
Goal Kicks                float64
Yellow cards                int64
Red cards                   int64
Fouls                       int64
Offsides                  float64
dtype: object

In [16]:
df.columns.tolist()

['Name',
 'Jersey Number',
 'Club',
 'Position',
 'Nationality',
 'Age',
 'Appearances',
 'Wins',
 'Losses',
 'Goals',
 'Goals per match',
 'Headed goals',
 'Goals with right foot',
 'Goals with left foot',
 'Penalties scored',
 'Freekicks scored',
 'Shots',
 'Shots on target',
 'Shooting accuracy %',
 'Hit woodwork',
 'Big chances missed',
 'Clean sheets',
 'Goals conceded',
 'Tackles',
 'Tackle success %',
 'Last man tackles',
 'Blocked shots',
 'Interceptions',
 'Clearances',
 'Headed Clearance',
 'Clearances off line',
 'Recoveries',
 'Duels won',
 'Duels lost',
 'Successful 50/50s',
 'Aerial battles won',
 'Aerial battles lost',
 'Own goals',
 'Errors leading to goal',
 'Assists',
 'Passes',
 'Passes per match',
 'Big chances created',
 'Crosses',
 'Cross accuracy %',
 'Through balls',
 'Accurate long balls',
 'Saves',
 'Penalties saved',
 'Punches',
 'High Claims',
 'Catches',
 'Sweeper clearances',
 'Throw outs',
 'Goal Kicks',
 'Yellow cards',
 'Red cards',
 'Fouls',
 'Offsides']

In [12]:
df['Position'].value_counts()

Position
Midfielder    198
Defender      194
Forward       110
Goalkeeper     69
Name: count, dtype: int64

In [16]:
mid_df=df[df['Position']=='Midfielder']
mid_df.shape

(198, 59)

In [20]:
mid_talent=mid_df[['Name','Club','Passes per match','Assists','Big chances created']]
mid_talent

,Name,Club,Passes per match,Assists,Big chances created
13,Mesut Özil,Arsenal,60.79,54,65.0
14,Lucas Torreira,Arsenal,39.57,3,3.0
15,Ainsley Maitland-Niles,Arsenal,34.57,3,4.0
16,Mohamed Elneny,Arsenal,53.87,3,2.0
17,Joseph Willock,Arsenal,12.06,1,1.0
...,...,...,...,...,...
561,Romain Saïss,Wolverhampton-Wanderers,45.43,1,4.0
562,João Moutinho,Wolverhampton-Wanderers,48.44,14,16.0
563,Leander Dendoncker,Wolverhampton-Wanderers,33.32,0,2.0
564,Vitinha,Wolverhampton-Wanderers,5.00,0,0.0
565,Meritan Shabani,Wolverhampton-Wanderers,0.00,0,0.0

In [5]:
df['Position'].value_counts()

Position
Midfielder    198
Defender      194
Forward       110
Goalkeeper     69
Name: count, dtype: int64

In [3]:
df[df['Age']<20]

,Name,Jersey Number,Club,Position,Nationality,Age,Appearances,Wins,Losses,Goals,...,Punches,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides
5,William Saliba,4.0,Arsenal,Defender,France,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
21,Bukayo Saka,7.0,Arsenal,Midfielder,England,19.0,28,11,7,1,...,NaN,NaN,NaN,NaN,NaN,NaN,6,0,22,13.0
28,Gabriel Martinelli,35.0,Arsenal,Forward,Brazil,19.0,14,3,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0,9,2.0
53,Jacob Ramsey,41.0,Aston-Villa,Midfielder,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
63,Tariq Lamptey,2.0,Brighton-and-Hove-Albion,Defender,England,19.0,11,4,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,3,0,16,0.0
71,Haydon Roberts,58.0,Brighton-and-Hove-Albion,Defender,England,18.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
82,Lars Dendoncker,53.0,Brighton-and-Hove-Albion,Midfielder,Belgium,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
102,Bobby Thomas,37.0,Burnley,Defender,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
136,Billy Gilmour,23.0,Chelsea,Midfielder,Scotland,19.0,6,5,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,3,0.0
141,Callum Hudson-Odoi,20.0,Chelsea,Forward,England,19.0,35,18,12,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0,12,6.0
145,Nathan Ferguson,NaN,Crystal-Palace,Defender,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
171,Brandon Pierrick,40.0,Crystal-Palace,Forward,England,18.0,2,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
181,Jarrad Branthwaite,32.0,Everton,Defender,England,18.0,4,1,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,4,0.0
183,Niels Nkounkou,18.0,Everton,Defender,France,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
203,Anthony Gordon,24.0,Everton,Forward,England,19.0,11,3,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,10,1.0
230,Elia Caprile,25.0,Leeds-United,Goalkeeper,Italy,19.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN
237,Oliver Casey,49.0,Leeds-United,Defender,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
238,Charlie Cresswell,35.0,Leeds-United,Defender,England,17.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
249,Mateusz Bogusz,44.0,Leeds-United,Midfielder,Poland,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
253,Joe Gelhardt,30.0,Leeds-United,Forward,England,18.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
266,Luke Thomas,33.0,Leicester-City,Defender,England,19.0,3,1,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0.0
296,Neco Williams,76.0,Liverpool,Defender,Wales,19.0,6,4,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0,5,0.0
299,Sepp van den Berg,72.0,Liverpool,Defender,Netherlands,18.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
307,Curtis Jones,17.0,Liverpool,Midfielder,England,19.0,7,6,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,4,0.0
309,Harvey Elliott,67.0,Liverpool,Midfielder,England,17.0,4,2,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
331,Eric García,50.0,Manchester-City,Defender,Spain,19.0,13,11,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0,9,0.0
339,Tommy Doyle,69.0,Manchester-City,Midfielder,England,18.0,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
340,Adrián Bernabé,82.0,Manchester-City,Midfielder,Spain,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
346,Liam Delap,48.0,Manchester-City,Forward,England,17.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
363,Teden Mengi,71.0,Manchester-United,Defender,England,18.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
377,Mason Greenwood,11.0,Manchester-United,Forward,England,18.0,35,14,10,10,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,12,5.0
381,Daniel Langley,41.0,Newcastle-United,Goalkeeper,England,19.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN
431,Zak Brunt,42.0,Sheffield-United,Midfielder,England,18.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
472,Dennis Cirkin,49.0,Tottenham-Hotspur,Defender,England,18.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
484,Harvey White,48.0,Tottenham-Hotspur,Midfielder,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
487,Jack Clarke,47.0,Tottenham-Hotspur,Forward,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
519,Jamie Soule,32.0,West-Bromwich-Albion,Forward,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
526,Gonçalo Cardoso,29.0,West-Ham-United,Defender,Portugal,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
532,Ajibola Alese,42.0,West-Ham-United,Defender,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
533,Harrison Ashby,50.0,West-Ham-United,Defender,Scotland,18.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
548,Emmanuel Longelo,56.0,West-Ham-United,Forward,England,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
558,Ki-Jana Hoever,2.0,Wolverhampton-Wanderers,Defender,Netherlands,18.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
569,Fábio Silva,17.0,Wolverhampton-Wanderers,Forward,Portugal,18.0,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0

In [4]:
df['league'].value_counts()

KeyError: 'league'

In [17]:
df['Shooting accuracy %']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
566    32%
567    35%
568    27%
569     0%
570     0%
Name: Shooting accuracy %, Length: 571, dtype: object

In [19]:
df.describe()

,Jersey Number,Age,Appearances,Wins,Losses,Goals,Goals per match,Headed goals,Goals with right foot,Goals with left foot,...,Punches,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides
count,563.000000,570.000000,571.000000,571.000000,571.000000,571.000000,309.000000,502.000000,502.000000,502.000000,...,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,571.000000,571.000000,571.000000,502.000000
mean,19.534636,25.789474,68.823117,28.957968,23.896673,7.327496,2.648414,1.414343,4.468127,2.388446,...,24.652174,45.869565,20.782609,25.565217,210.000000,414.144928,7.917688,0.301226,53.033275,11.063745
std,14.273515,4.377354,81.797516,38.969376,28.488376,16.810490,8.002117,3.433374,11.048341,6.295652,...,46.282644,82.332167,43.058397,47.333758,334.822473,641.246265,11.556811,0.698607,75.605560,26.570058
min,1.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,22.000000,3.000000,1.000000,1.000000,0.000000,0.050000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,18.000000,26.000000,36.000000,12.000000,14.000000,1.000000,0.140000,0.000000,1.000000,0.000000,...,2.000000,6.000000,3.000000,4.000000,39.000000,53.000000,3.000000,0.000000,22.000000,2.000000
75%,27.000000,29.000000,108.000000,41.000000,36.000000,6.000000,0.390000,1.000000,3.000000,2.000000,...,31.000000,45.000000,17.000000,28.000000,300.000000,527.000000,11.000000,0.000000,74.000000,8.750000
max,82.000000,38.000000,539.000000,272.000000,158.000000,180.000000,57.000000,31.000000,127.000000,63.000000,...,269.000000,391.000000,249.000000,257.000000,1516.000000,2806.000000,81.000000,5.000000,438.000000,203.000000

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 59 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    571 non-null    object
 1   Jersey Number           563 non-null    float64
 2   Club                    571 non-null    object
 3   Position                571 non-null    object
 4   Nationality             570 non-null    object
 5   Age                     570 non-null    float64
 6   Appearances             571 non-null    int64
 7   Wins                    571 non-null    int64
 8   Losses                  571 non-null    int64
 9   Goals                   571 non-null    int64
 10  Goals per match         309 non-null    float64
 11  Headed goals            502 non-null    float64
 12  Goals with right foot   502 non-null    float64
 13  Goals with left foot    502 non-null    float64
 14  Penalties scored        309 non-null    float64
 15  Freekicks scored        309 non-null    float64
 16  Shots                   309 non-null    float64
 17  Shots on target         309 non-null    float64
 18  Shooting accuracy %     309 non-null    object
 19  Hit woodwork            502 non-null    float64
 20  Big chances missed      309 non-null    float64
 21  Clean sheets            262 non-null    float64
 22  Goals conceded          262 non-null    float64
 23  Tackles                 502 non-null    float64
 24  Tackle success %        390 non-null    object
 25  Last man tackles        193 non-null    float64
 26  Blocked shots           502 non-null    float64
 27  Interceptions           502 non-null    float64
 28  Clearances              502 non-null    float64
 29  Headed Clearance        502 non-null    float64
 30  Clearances off line     193 non-null    float64
 31  Recoveries              390 non-null    float64
 32  Duels won               390 non-null    float64
 33  Duels lost              390 non-null    float64
 34  Successful 50/50s       390 non-null    float64
 35  Aerial battles won      390 non-null    float64
 36  Aerial battles lost     390 non-null    float64
 37  Own goals               262 non-null    float64
 38  Errors leading to goal  459 non-null    float64
 39  Assists                 571 non-null    int64
 40  Passes                  571 non-null    int64
 41  Passes per match        571 non-null    float64
 42  Big chances created     502 non-null    float64
 43  Crosses                 502 non-null    float64
 44  Cross accuracy %        390 non-null    object
 45  Through balls           390 non-null    float64
 46  Accurate long balls     459 non-null    float64
 47  Saves                   69 non-null     float64
 48  Penalties saved         69 non-null     float64
 49  Punches                 69 non-null     float64
 50  High Claims             69 non-null     float64
 51  Catches                 69 non-null     float64
 52  Sweeper clearances      69 non-null     float64
 53  Throw outs              69 non-null     float64
 54  Goal Kicks              69 non-null     float64
 55  Yellow cards            571 non-null    int64
 56  Red cards               571 non-null    int64
 57  Fouls                   571 non-null    int64
 58  Offsides                502 non-null    float64
dtypes: float64(43), int64(9), object(7)
memory usage: 263.3+ KB